### ISSUE TITLE
[Android] - The ad size and ad unit ID must be set before loadAd is called

### ISSUE THREAD

**Issue by jbernhardt23** [NZME/react-native-ad-manager#89]
iOS loads the example banner properly but on Android I'm getting this error:
This exception does not get returned in the `onAdFailedToLoad` but connected to Android studio I see this: 

`  E  Unhandled SoftException
                                                                                                    java.lang.IllegalStateException: The ad size and ad unit ID must be set before loadAd is called.
                                                                                                    	at com.google.android.gms.internal.ads.zzbhl.zzh(com.google.android.gms:play-services-ads-lite@@20.5.0:1)
                                                                                                    	at com.google.android.gms.ads.admanager.AdManagerAdView.loadAd(com.google.android.gms:play-services-ads-lite@@20.5.0:1)
                                                                                                    	at com.matejdr.admanager.BannerAdView.loadBanner(BannerAdView.java:279)
                                                                                                    	at com.matejdr.admanager.RNAdManagerBannerViewManager.receiveCommand(RNAdManagerBannerViewManager.java:201)
                                                                                                    	at com.matejdr.admanager.RNAdManagerBannerViewManager.receiveCommand(RNAdManagerBannerViewManager.java:27)
                                                                                                    	at com.facebook.react.uimanager.NativeViewHierarchyManager.dispatchCommand(NativeViewHierarchyManager.java:832)
                                                                                                    	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchCommandOperation.executeWithExceptions(UIViewOperationQueue.java:323)
                                                                                                    	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:879)
                                                                                                    	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1025)
                                                                                                    	at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
                                                                                                    	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1085)
                                                                                                    	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
                                                                                                    	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
                                                                                                    	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:984)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:764)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:696)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:873)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:214)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7073)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)`
 Versions:
 ` "@react-native-firebase/app": "^12.9.3"`
 `"react-native": "0.65.3",`

**Comment by aleccolville-nzme** [comment]
closing issue as v2 has been released
